include: package:lint/strict.yaml

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/**/injection.config.dart
  errors:
    todo: true

linter:
  rules:
    prefer_single_quotes: true
    sort_constructors_first: true
